### ISSUE TITLE
起来起来不愿做奴隶的人们

### ISSUE THREAD

**Issue by yaoshanliang** [fuck-xuexiqiangguo/Fuck-XueXiQiangGuo#101]

**Comment by AdventCirno** [comment]
贴吧一宣传我看是要完蛋,但愿作者不要被这些人气的不更新或者删除了

**Comment by flamehaze1115** [comment]
自己目的不纯非要入党，学习强国就是要把你们这些动机不良的假党员逼出去

**Comment by AnywherePear** [comment]
这是低级红还是高级黑.
On Fri, Mar 08, 2019 at 04:51:08AM -0800, Xiaoxiao LONG wrote:
" 自己目的不纯非要入党，学习强国就是要把你们这些动机不良的假党员逼出去
" 
" -- 
" You are receiving this because you are subscribed to this thread.
" Reply to this email directly or view it on GitHub:
" https://github.com/fuck-xuexiqiangguo/Fuck-XueXiQiangGuo/issues/101#issuecomment-470917770
